

/*Variable name label formats*/
PROC FORMAT;
    VALUE $namelabels
	"ACI" = "Acute coronary insuff."
	"AP" = "Angina pectoris"
	"Adhx15Bin" = "Adherence"
	"AntiArr" = "Antiarrhythmic meds."
	"AntiHyp" = "Antihypertensive meds."
	"AnyQQS" = "Q/QS pattern"
	"AnySTDep" = "ST depression"
	"AnyTwave" = "T-wave"
	"CHF" = " Congestive heart failure"
	"CIG" = "Smoking"
	"CardioM" = "Cardiomegaly"
	"DIG" = "Digitalis"
	"DIUR" = "Diuretics"
	"FVEB" = "Premature ventricular beats"
	"HiBili" = "Bilirubin"
	"HiDiasBP" = "Diastolic BP"
	"HiFastGluc" = "Fasting glucose"
	"HiHeart" = "Heart rate"
	"HiHemat" = "Hematocrit"
	"HiNeut" = "Neutrophils"
	"HiOneGluc" = "One-hour glucose"
	"HiPlasUrea" = "Urea nitrogen"
	"HiSerAlk" = "Alkaline phosphatase"
	"HiSerChol" = "Cholesterol"
	"HiSerTrigly" = "Triglycerides"
	"HiSerUric" = "Uric acid"
	"HiSysBP" = "Systolic BP"
	"HiWhiteCell" = "White cell count"
	"IC" = "Int. claudication"
	"ICIA" = "Int. cerebral ischemic attack"
	"INACT" = "Physical activity"
	"IRK" = "Risk group"
	"NIHA_bin1" = "NYHA functional class"
	"OralHyp" = "Hypoglycemic meds."
	"STElev" = "ST elevation"
	"VCD" = "Ventricular conduction defect"
	"age_bin" = "Age"
	"dth5" = "Death"
	"mi_bin" = "Prior heart attacks"
	"nonwhite" = "Race"
	"rbw_bin" = "Weight"
    ;
RUN;
